security/urls.py
from django.urls import path
from . import views

app_name = 'security'

urlpatterns = [
  path('', views.home, name='home'),
  path('parse-upload', views.parseUpload, name='parse-upload'),
  path('required-items', views.requiredItems, name='required-items'),
  path('history', views.history, name='history'),
  path('history_view/<str:creation_date>/', views.history_viewer, name='history_view'),
  path('download-file/<id>', views.downloadFile, name='download-file'),
  path('POconversion', views.POconversion, name='POconversion'),
  path('dbchange', views.auto_matching_DB_changer, name='dbchange'),
  path('viewer', views.viewer, name='viewer'),
  path('export-doubleIgnore', views.live_doubleIgnore, name='export-file'),
  path('export-doubleUpdate', views.live_doubleUpdate, name='export-file'),
  path('history-delete', views.history_deletion, name='history-delete')
]

securityauth/urls.py
from django.urls import path
from . import views

app_name = 'securityauth'

urlpatterns = [
  path('signin/', views.signin, name='signin'),
  path('signup/', views.signup, name='signup'),
]

securitydbmanage/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('securityauth.urls', namespace='securityauth')),
    path('', include('security.urls', namespace='security'))
]

security/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model


User = get_user_model()
# Create your models here.
class ProcessHistory(models.Model):
  user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
  input = models.CharField(max_length=255, null=True)
  output = models.CharField(max_length=255, null=True)
  created_at = models.DateTimeField(auto_now_add=True)
  updated_at = models.DateTimeField(auto_now=True)
  

securityauth/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class CustomUser(AbstractUser):
  is_allowed = models.BooleanField(default=False)
# Create your models here.

security/forms.py
from django import forms
from django.core.validators import FileExtensionValidator
from .models import ProcessHistory

class ProcessForm(forms.Form):
  data = forms.FileField(widget=forms.ClearableFileInput(attrs={"allow_multiple_selected": True}), validators=[FileExtensionValidator(['pdf', 'xlsx', 'xls'])])
  additions = forms.CharField(widget=forms.Textarea)
  input = forms.CharField(widget=forms.Textarea)
  customername = forms.CharField(max_length=255)
  currency = forms.CharField(max_length=10)

# class HistoryForm(forms.Form):

securityauth/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model


User = get_user_model()
class SigninForm(forms.Form):
  def __init__(self, *args, **kwargs):
    super().__init__(*args, **kwargs)
    for field in self.fields.values():
        field.widget.attrs['class'] = 'form-control'
  email = forms.EmailField(required=True)
  password = forms.CharField(min_length=8, max_length=100, required=True, widget=forms.PasswordInput)

class SignupForm(forms.Form):
  def __init__(self, *args, **kwargs):
    super().__init__(*args, **kwargs)
    for field in self.fields.values():
        field.widget.attrs['class'] = 'form-control'
  email = forms.EmailField(required=True)
  password = forms.CharField(min_length=8, max_length=100, required=True, widget=forms.PasswordInput)
  confirm_password = forms.CharField(min_length=8, max_length=100, required=True, widget=forms.PasswordInput)

  def clean_email(self):
    email = self.cleaned_data['email']
    if User.objects.filter(email=email).exists():
        raise forms.ValidationError('This email is already in use.')
    return email

securityauth/views.py
from django.shortcuts import render, redirect
# from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login
from django.contrib.auth.hashers import make_password
from . import forms
from django.contrib.auth import get_user_model

User = get_user_model()

# Create your views here.
def signin(request):
  if request.method == 'POST':
    form = forms.SigninForm(request.POST)
    if form.is_valid():
      username = form.cleaned_data['email']
      password = form.cleaned_data['password']
      user = authenticate(request, username=username, password=password)
      if user is not None:
        print('user is found')
        if user.is_allowed is False:
          print('user is not allowed')
          form.add_error(None, 'You are not allowed yet.')
          return render(request, 'signin.html', { 'form': forms.SigninForm ,'is_signup_page': False})
        login(request, user)
        return redirect('security:home')  # Replace 'home' with the URL name of your home page
      else:
        print('user is not found')
        form.add_error(None, 'Invalid username or password.')
  else:
     form = forms.SigninForm()
  return render(request, 'signin.html', { 'form': forms.SigninForm,'is_signup_page': False })

def signup(request):
  if request.method == 'POST':
    form = forms.SignupForm(request.POST)
    if form.is_valid():
      username = form.cleaned_data['email']
      password = form.cleaned_data['password']
      User.objects.create(username=username, email=username, password=make_password(password))
      return redirect('securityauth:signin')
    return render(request, 'signup.html', {'form': form, 'is_signup_page': True})    
  return render(request, 'signup.html', { 'form': forms.SignupForm, 'is_signup_page': True })

securityauth/templates/signin.html
{% extends 'layouts/layout.html' %}

{% block content %}
  <div class="sign-card-header">
    <h3 class="text-center">Sign In</h3>
  </div>
  <div class="card-body px-5">
    {% if form.non_field_errors %}
      <div class="alert alert-danger">
        {% for error in form.non_field_errors %}
          {{ error }}
        {% endfor %}
      </div>
    {% endif %}
    <form method="POST" class="pb-5">
      {% csrf_token %}
      <div class="form-group mb-3 label-pos">
        <label for="{{ form.email.id_for_label }}" class="form-label label-pos-static">Email*</label>
        <div class="email-input">{{ form.email }}</div>
        {{ form.email.errors }}
      </div>
      <div class="form-group mb-3  label-pos">
        <label for="{{ form.password.id_for_label }}" class="form-label label-pos-static">Password*</label>
        <div class="email-password ">
          {{ form.password }}
          <div class="input-group-addon" onclick="togglePasswordVisibility()">
            <i class="bi bi-eye" id="togglePassword"></i>
          </div>
        </div>
        {{ form.password.errors }}
      </div>   
      <div class="mt-5 d-flex justify-content-end">
        <button type="submit" class="btn-card-sign">Sign In</button>
      </div>
      <!-- <a href="{% url 'securityauth:signup' %}">Sign Up</a> -->
    </form>
  </div>
  <script>
    function togglePasswordVisibility() {
      const passwordInput = document.getElementById('{{ form.password.id_for_label }}');
      const passwordIcon = document.getElementById('togglePassword');

      if (passwordInput.type === 'password') {
          passwordInput.type = 'text';
          passwordIcon.classList.remove('bi-eye');
          passwordIcon.classList.add('bi-eye-slash');
      } else {
          passwordInput.type = 'password';
          passwordIcon.classList.remove('bi-eye-slash');
          passwordIcon.classList.add('bi-eye');
      }
    }
  </script>
{% endblock %}

securityauth/templates/signup.html
{% extends 'layouts/layout.html' %}

{% block content %}
  <div class="sign-card-header">
    <h3 class="text-center">Sign Up</h3>
  </div>
  <div class="card-body  px-5">
    <form method="POST">
      {% csrf_token %}
      <div class="form-group mb-3">
        <label for="{{ form.email.id_for_label }}" class="form-label">Email:</label>
        {{ form.email }}
        {{ form.email.errors }}
      </div>
      <div class="form-group mb-3">
        <label for="{{ form.password.id_for_label }}">Password:</label>
        {{ form.password }}
        {{ form.password.errors }}
      </div>   
      <div class="form-group mb-3">
        <label for="{{ form.password.id_for_label }}">Confirm Password:</label>
        {{ form.confirm_password }}
        {{ form.confirm_password.errors }}
      </div>
      <div class="mt-5 d-flex justify-content-end">
        <button type="submit" class="btn-card-sign">Sign Up</button>
      </div>
      <!-- <a href="{% url 'securityauth:signin' %}">Sign In</a> -->
    </form>
  </div>
{% endblock %}