security/urls.py
from django.urls import path
from . import views

app_name = 'security'

urlpatterns = [
  path('', views.home, name='home'),
  path('parse-upload', views.parseUpload, name='parse-upload'),
  path('required-items', views.requiredItems, name='required-items'),
  path('history', views.history, name='history'),
  path('history_view/<str:creation_date>/', views.history_viewer, name='history_view'),
  path('download-file/<id>', views.downloadFile, name='download-file'),
  path('POconversion', views.POconversion, name='POconversion'),
  path('dbchange', views.auto_matching_DB_changer, name='dbchange'),
  path('viewer', views.viewer, name='viewer'),
  path('export-doubleIgnore', views.live_doubleIgnore, name='export-file'),
  path('export-doubleUpdate', views.live_doubleUpdate, name='export-file'),
  path('history-delete', views.history_deletion, name='history-delete')
]

securityauth/urls.py
from django.urls import path
from . import views

app_name = 'securityauth'

urlpatterns = [
  path('signin/', views.signin, name='signin'),
  path('signup/', views.signup, name='signup'),
]

securitydbmanage/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('securityauth.urls', namespace='securityauth')),
    path('', include('security.urls', namespace='security'))
]

security/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model


User = get_user_model()
# Create your models here.
class ProcessHistory(models.Model):
  user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
  input = models.CharField(max_length=255, null=True)
  output = models.CharField(max_length=255, null=True)
  created_at = models.DateTimeField(auto_now_add=True)
  updated_at = models.DateTimeField(auto_now=True)
  

securityauth/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class CustomUser(AbstractUser):
  is_allowed = models.BooleanField(default=False)
# Create your models here.

security/forms.py
from django import forms
from django.core.validators import FileExtensionValidator
from .models import ProcessHistory

class ProcessForm(forms.Form):
  data = forms.FileField(widget=forms.ClearableFileInput(attrs={"allow_multiple_selected": True}), validators=[FileExtensionValidator(['pdf', 'xlsx', 'xls'])])
  additions = forms.CharField(widget=forms.Textarea)
  input = forms.CharField(widget=forms.Textarea)
  customername = forms.CharField(max_length=255)
  currency = forms.CharField(max_length=10)

# class HistoryForm(forms.Form):

securityauth/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model


User = get_user_model()
class SigninForm(forms.Form):
  def __init__(self, *args, **kwargs):
    super().__init__(*args, **kwargs)
    for field in self.fields.values():
        field.widget.attrs['class'] = 'form-control'
  email = forms.EmailField(required=True)
  password = forms.CharField(min_length=8, max_length=100, required=True, widget=forms.PasswordInput)

class SignupForm(forms.Form):
  def __init__(self, *args, **kwargs):
    super().__init__(*args, **kwargs)
    for field in self.fields.values():
        field.widget.attrs['class'] = 'form-control'
  email = forms.EmailField(required=True)
  password = forms.CharField(min_length=8, max_length=100, required=True, widget=forms.PasswordInput)
  confirm_password = forms.CharField(min_length=8, max_length=100, required=True, widget=forms.PasswordInput)

  def clean_email(self):
    email = self.cleaned_data['email']
    if User.objects.filter(email=email).exists():
        raise forms.ValidationError('This email is already in use.')
    return email

securityauth/views.py
from django.shortcuts import render, redirect
# from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login
from django.contrib.auth.hashers import make_password
from . import forms
from django.contrib.auth import get_user_model

User = get_user_model()

# Create your views here.
def signin(request):
  if request.method == 'POST':
    form = forms.SigninForm(request.POST)
    if form.is_valid():
      username = form.cleaned_data['email']
      password = form.cleaned_data['password']
      user = authenticate(request, username=username, password=password)
      if user is not None:
        print('user is found')
        if user.is_allowed is False:
          print('user is not allowed')
          form.add_error(None, 'You are not allowed yet.')
          return render(request, 'signin.html', { 'form': forms.SigninForm ,'is_signup_page': False})
        login(request, user)
        return redirect('security:home')  # Replace 'home' with the URL name of your home page
      else:
        print('user is not found')
        form.add_error(None, 'Invalid username or password.')
  else:
     form = forms.SigninForm()
  return render(request, 'signin.html', { 'form': forms.SigninForm,'is_signup_page': False })

def signup(request):
  if request.method == 'POST':
    form = forms.SignupForm(request.POST)
    if form.is_valid():
      username = form.cleaned_data['email']
      password = form.cleaned_data['password']
      User.objects.create(username=username, email=username, password=make_password(password))
      return redirect('securityauth:signin')
    return render(request, 'signup.html', {'form': form, 'is_signup_page': True})    
  return render(request, 'signup.html', { 'form': forms.SignupForm, 'is_signup_page': True })

security/templates/layouts/base.html
{% load static %}
<!DOCTYPE html>

<html class="light-style layout-navbar-fixed layout-menu-fixed layout-menu-collapsed">
  <head>
    <title>History Page</title>
    <link rel="stylesheet" type="text/css" href="{% static 'security/css/home.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/cdbootstrap/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/cdbootstrap/css/cdb.min.css"/>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css">
    <link href="https://www.cssscript.com/demo/sticky.css" rel="stylesheet" type="text/css">
    <link href="https://unpkg.com/boxicons@2.0.9/css/boxicons.min.css" rel="stylesheet"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Favicon -->
    {% comment %} <link rel="icon" type="image/x-icon" href="../../assets/img/favicon/favicon.ico" /> {% endcomment %}

    <!-- Icons -->
    <link rel="stylesheet" href="{% static 'security/vendor/fonts/fontawesome.css' %}" />
    <link rel="stylesheet" href="{% static 'security/vendor/fonts/tabler-icons.css' %}" />
    <link rel="stylesheet" href="{% static 'security/vendor/fonts/flag-icons.css' %}" />

    <!-- Core CSS -->
    <link rel="stylesheet" href="{% static 'security/vendor/css/rtl/core.css' %}" class="template-customizer-core-css" />
    <link rel="stylesheet" href="{% static 'security/vendor/css/rtl/theme-default.css' %}" class="template-customizer-theme-css" />
    <link rel="stylesheet" href="{% static 'security/vendor/libs/toastr/toastr.css' %}" />
    <link rel="stylesheet" href="{% static 'security/css/demo.css' %}" />
    <link rel="stylesheet" href="{% static 'security/css/custom.css' %}">

    <!-- Helpers -->
    <script src="{% static 'security/vendor/js/helpers.js' %}"></script>

    <script src="{% static 'security/js/config.js' %}"></script>
  </head>

  <body>
    <!-- Layout wrapper -->
    <div class="layout-wrapper layout-content-navbar">
      <div class="layout-container">
        <!-- Menu -->

        <aside id="layout-menu" class="layout-menu menu-vertical menu bg-menu-theme">
          <div class="app-brand demo">
            <a href="{% url 'security:home' %}" class="app-brand-link logo-name-wrapper m-0">
              <span class="app-brand-logo demo">
                <img src="{% static 'security/image/logo.png' %}" width="46" heigh="46">
              </span>
              {% comment %} <span class="app-brand-text demo menu-text fw-bold">Dashboard</span> {% endcomment %}
            </a>

            <a href="javascript:void(0);" class="layout-menu-toggle menu-link text-large ms-auto d-none">
              <i class="ti menu-toggle-icon d-none d-xl-block ti-sm align-middle"></i>
              <i class="ti ti-x d-block d-xl-none ti-sm align-middle"></i>
            </a>
          </div>

          <div class="menu-inner-shadow"></div>

          <ul class="menu-inner py-1">
            <li class="menu-item">
              <a href="{% url 'security:home' %}" class="menu-link">
                <i class="menu-icon fa-icons fa fas fa-gauge text-light-blue"></i>
                <div data-i18n="Email">Home</div>
              </a>
            </li>
            <li class="menu-item">
              <a href="{% url 'security:POconversion' %}" class="menu-link">
                <i class="menu-icon fa-icons fas fa-briefcase text-light-blue"></i>
                <div data-i18n="Chat">POconversion</div>
              </a>
            </li>
            <li class="menu-item">
              <a href="{% url 'securityauth:signin' %}" class="menu-link">
                <i class="menu-icon fas fa-right-from-bracket text-light-blue"></i>
                <div data-i18n="Chat">Log out</div>
              </a>
            </li>
          </ul>
        </aside>
        <!-- / Menu -->

        <!-- Layout container -->
        <div class="layout-page">
          <!-- Navbar -->

          <nav
            class="layout-navbar container-xxl navbar navbar-expand-xl navbar-detached align-items-center bg-navbar-theme"
            id="layout-navbar"
          >
            <div class="layout-menu-toggle navbar-nav align-items-xl-center me-3 me-xl-0 d-xl-none">
              <a class="nav-item nav-link px-0 me-xl-4" href="javascript:void(0)">
                <i class="ti ti-menu-2 ti-sm"></i>
              </a>
            </div>

            <div class="navbar-nav-right d-flex align-items-center" id="navbar-collapse">
              <!-- Search -->
              <a href="{% url 'security:home' %}" class="navbar-nav align-items-center fs-20px text-dark-gray">
                Dashboard
              </a>
              <!-- /Search -->

              <a class="navbar-brand" href="{% url 'security:history' %}" style="display: flex; align-items: center;"><span class="history-text"> History</span></a>
            </div>
          </nav>

          <!-- / Navbar -->

          <!-- Content wrapper -->
          <div class="content-wrapper">
            <!-- Content -->

            <div class="container-xxl flex-grow-1 container-p-y">
              {% block content %}
              {% endblock content %}
            </div>
            <div id="historycontain" style="background-color: #f1f1f1;">
              {% block history_content %}
              {% endblock history_content %}
            </div>

            <div class="content-backdrop fade"></div>
          </div>
          <!-- Content wrapper -->
        </div>
        <!-- / Layout page -->
      </div>
    </div>
    <!-- / Layout wrapper -->

    <!-- Core JS -->
    <script src="{% static 'security/vendor/libs/jquery/jquery.js' %}"></script>
    <script src="{% static 'security/vendor/libs/popper/popper.js' %}"></script>
    <script src="{% static 'security/vendor/libs/toastr/toastr.js' %}"></script>
    <script src="{% static 'security/vendor/js/bootstrap.js' %}"></script>
    
    <script src="{% static 'security/vendor/js/menu.js' %}"></script>
    <!-- endbuild -->

    <!-- Vendors JS -->

    <!-- Main JS -->
    <script src="{% static 'security/js/main.js' %}"></script>

    <script src="https://cdn.jsdelivr.net/npm/cdbootstrap/js/bootstrap.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/cdbootstrap/js/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/cdbootstrap/js/cdb.min.js"></script>
    <script src="{% static 'security/js/home.js' %}"></script>
    {% comment %} <script src="{% static 'security/js/history.js' %}"></script> {% endcomment %}
    <script src="https://kit.fontawesome.com/c84a4c5774.js" crossorigin="anonymous"></script>
    <script src="https://unpkg.com/xlsx/dist/xlsx.full.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" >
    <script type="text/javascript">
        {
          let sideBar = document.querySelector('.home-side-bar');
          let mainPage = document.querySelector('.home-contain');
          let arrowCollapse = document.querySelector('#logo-name__icon');
          let logo = document.querySelector(".logo-name-wrapper");
          logo.onclick = () => {
            mainPage.classList.toggle('collapse-home-contain');
            sideBar.classList.toggle('collapse-home');
            arrowCollapse.classList.toggle('collapse-home');
            if (arrowCollapse.classList.contains('collapse-home')) {
              arrowCollapse.classList =
                'bx bx-arrow-from-left logo-name__icon collapse-home';
            } else {
              arrowCollapse.classList = 'bx bx-arrow-from-right logo-name__icon';
            }
          };
        }
    </script>
    <script>
      $(document).ready(function() {
        $("#layout-menu ul a.menu-link").each((index, ele) => {
          if(ele.href == window.location.href) {
            $(ele).addClass('active');
          }
        })
      });
    </script>
    {% block scripts %}
    {% endblock scripts %}
  </body>
</html>